### ISSUE TITLE
the repo doesn't seem complete

### ISSUE THREAD

**Issue by Atul-Anand-Jha** [BassemMohamed/Arabic-English-Subtitling#1]
there are many files missing. Like, model file and others.. Even the sh script file has absolute paths mentioned. How, Can i get the completely working demo. ?

**Comment by bassem-i** [comment]
Hey Atul, Some files are too big to be added here.

Also, This repo was my graduation project a couple of years ago, I am sure it's not really organized. I will try to find some time to get it working again. No promises though 😊

**Comment by Atul-Anand-Jha** [comment]
Oh, I got the point. Even i had encountered a similar issue once.

what was an approx accuracy with the auto-shell file ? any rough figure
that you can recall...?

**Comment by Atul-Anand-Jha** [comment]
Which arabic accent model, is that on which u have trained your model ?
I am specifically looking for Barhraini Accent. Do you have any leads for that.

Thanks for your time.
